name: sample
option:
  team: rerost
jobs:
  - name: jobA
    command: "echo A"
    option:
      repo: repo
  - name: jobB
    command: "echo B"
    dependencies: [jobA]
    option:
      repo: repo
  - name: jobC
    command: "echo C"
    dependencies: [jobB]
    option:
      repo: repo
  - name: jobD
    command: "echo D"
    dependencies: [jobB, jobC]
    option:
      repo: repo
